LoginPage/Pages/Edit_page.cshtml.cs
using Azure;
using LoginPage.Data.Context;
using LoginPage.Data.Entity;
using LoginPage.Pages.Shared.RegisterModelClass;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LoginPage.Pages
{
    public class Edit_pageModel : PageModel
    {
        private readonly AppDbContext _context;

        [BindProperty]
        public Customer Customer { get; set; }  


        public Edit_pageModel(AppDbContext context)
        {
            _context = context;
        }

        public void OnGet()
        {
            
        }
        public void OnGetEdit(int? id)
        {
            var user =_context.customers.Find(id);
            Customer = user;
        }
        public IActionResult OnPostSubmit()
        {
            var user = _context.customers.Find(Customer.Id);
            if (user != null)
            {
                user.Name = Customer.Name;
                user.Email = Customer.Email;
                user.Password = Customer.Password;
                user.Age = Customer.Age;
                _context.SaveChanges();
            }

            return RedirectToPage("AdminHome");
        }

    }
}

LoginPage/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace LoginPage.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

LoginPage/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LoginPage.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public string CourseList { get; set; }

        public List<SelectListItem> Course { get; set; }

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            Course = new List<SelectListItem>
            {
                new SelectListItem{Value = "one", Text = "Option 1" },
                new SelectListItem{Value = "two", Text = "Option 2" },
                new SelectListItem{Value = "Three", Text = "Option 3" }
            };

            //if (TempData["isLogin"] == null)
            //{
            //    return RedirectToPage("/Signup");
            //}
            //return Page();

        }
    }
}

LoginPage/Pages/Newwork.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LoginPage.Pages
{
    public class Index1Model : PageModel
    {
        public void OnGet()
        {
        }
    }
}

LoginPage/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LoginPage.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

LoginPage/Pages/Product.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LoginPage.Pages
{
    public class ProductModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

LoginPage/Pages/Register.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using LoginPage.Pages.Shared.RegisterModelClass;
using Microsoft.AspNetCore.Mvc.Rendering;
using LoginPage.Data.Context;
using LoginPage.Data.Entity;

namespace LoginPage.Pages
{
    public class RegisterModel : PageModel
    {

        private readonly AppDbContext _context;

        public readonly IWebHostEnvironment _environment;

        public RegisterModel(AppDbContext context, IWebHostEnvironment _env)
        {
            _context = context;
            _environment = _env;
        }



        [BindProperty]
        public RegisterModelClass RegistredUser { get; set; }

        public void PopulateOptions()
        {
            if (RegistredUser == null)
            {
                RegistredUser = new RegisterModelClass();
            }

            RegistredUser.Gender = new List<SelectListItem> {
             new SelectListItem {Value="M",Text="Male"},
             new SelectListItem {Value="F",Text="Female"},
             new SelectListItem {Value="O",Text="Others"},
            };
        }
        public IActionResult OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page(); 
        
            }
            var filename = Guid.NewGuid().ToString() + Path.GetExtension(RegistredUser.ImageFile.FileName);

            var filepath = Path.Combine(_environment.WebRootPath,"Upload", filename);

            var fileStream = new FileStream(filepath, FileMode.Create);
            RegistredUser.ImageFile.CopyToAsync(fileStream);

            var newCus = new Customer
            {
                Name = RegistredUser.Username,
                Email = RegistredUser.Email,
                Password = RegistredUser.Password,
                ConfirmPassword=RegistredUser.ConfirmPassword,
                Age = RegistredUser.Age,
                ImgPath=filename
            }; 
            _context.customers.Add(newCus);
            _context.SaveChanges();
            TempData["Message"] = "Account Created Successfully";
            TempData["link"] = "/Signup";
            return RedirectToPage("Response");
        }

        public void OnGet()
        {
            PopulateOptions();
        }

    }
}

LoginPage/Pages/Response.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LoginPage.Pages
{
    public class ResponseModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

LoginPage/Pages/Signup.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using LoginPage.Pages.SignupModel;
using LoginPage.Data.Context;
using Microsoft.EntityFrameworkCore;

namespace LoginPage.Pages
{
    public class SignUpModel : PageModel
    {
        private readonly AppDbContext _context;

        public SignUpModel(AppDbContext context)
        {
            _context = context;
        }


        [BindProperty]
        public SignupModelClass User { get; set; }
        public void OnGet()
        {
            Console.WriteLine(TempData["Message"]);
        }
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
            return Page();
            }
            
            var getUsers= _context.customers
                          .Where(x => x.Email == User.Username && x.Password==User.Password)
                          .FirstOrDefault();

            if (getUsers != null) {   
            TempData["Message"] = "Login Success";
            TempData["link"] = "/Index";
                //TempData["isLogin"] = "True";
            return RedirectToPage("Response");            
            }
            TempData["LoginError"] = "Account Dosent Exist please provide valid credentials";
            return Page();
        }
    }
}

LoginPage/Pages/Edit_page.cshtml
@page
@model LoginPage.Pages.Edit_pageModel
@{
}

<h2>Edit User</h2>



<form method="post" asp-asp-page-handler="Submit">
   

    <div class="form-group">
        <input type="hidden" asp-for="Customer.Id" />
        <label asp-for="@Model.Customer.Name" class="control-label">Name</label>
        <input asp-for="@Model.Customer.Name" class="form-control" />
        <span asp-validation-for="@Model.Customer.Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="@Model.Customer.Email" class="control-label">Email</label>
        <input asp-for="@Model.Customer.Email" class="form-control" />
        <span asp-validation-for="@Model.Customer.Email" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="@Model.Customer.Password" class="control-label">Password</label>
        <input asp-for="@Model.Customer.Password" class="form-control" type="password" />
        <span asp-validation-for="@Model.Customer.Password" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="@Model.Customer.ConfirmPassword" class="control-label"></label>
        <input asp-for="@Model.Customer.ConfirmPassword" class="form-control" type="password" />
        <span asp-validation-for="@Model.Customer.ConfirmPassword" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="@Model.Customer.Age" class="control-label">Age :</label>
        <input asp-for="@Model.Customer.Age" class="form-control" />
        <span asp-validation-for="@Model.Customer.Age" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Register</button>
</form>

LoginPage/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <div class="form-group">
    <div class="btn-container">
        <button class="btn btn-secondary"><a class="text-light" asp-page="/AdminLogin">Admin Login</a> </button>
    </div>
    </div>

    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LoginPage/Pages/Newwork.cshtml
@page
@model LoginPage.Pages.Index1Model
@{
}

LoginPage/Pages/Product.cshtml
@page
@model LoginPage.Pages.ProductModel
@{
}
<h1>Product Home Page</h1>
<h3>Product list</h3>
<table class="table-bordered p-3">
    <tr>
        <th>Name</th>
    </tr>

LoginPage/Pages/Register.cshtml
@page "/Register"
@model LoginPage.Pages.RegisterModel
@{
}

<h2>User Registration</h2>

<form method="post" enctype="multipart/form-data" >
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="RegistredUser.Username" class="control-label"></label>
        <input asp-for="RegistredUser.Username" class="form-control" />
        <span asp-validation-for="RegistredUser.Username" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="RegistredUser.Email" class="control-label"></label>
        <input asp-for="RegistredUser.Email" class="form-control" />
        <span asp-validation-for="RegistredUser.Email" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="RegistredUser.Password" class="control-label"></label>
        <input asp-for="RegistredUser.Password" class="form-control" type="password" />
        <span asp-validation-for="RegistredUser.Password" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="RegistredUser.ConfirmPassword" class="control-label"></label>
        <input asp-for="RegistredUser.ConfirmPassword" class="form-control" type="password" />
        <span asp-validation-for="RegistredUser.ConfirmPassword" class="text-danger"></span>
    </div>

    <div class="form-group">       
            <label asp-for="RegistredUser.Age" class="control-label">Age :</label>
            <input asp-for="RegistredUser.Age" class="form-control" />
            <span asp-validation-for="RegistredUser.Age" class="text-danger"></span>
    </div>
     <div class="form-group">
        <label asp-for="RegistredUser.SelectGender" class="control-label">Gender</label>
        <select  asp-for="RegistredUser.SelectGender" asp-items="Model.RegistredUser.Gender" class="form-control" >
            <option value="">Select the Gender</option>
        </select>
        <span asp-validation-for="RegistredUser.SelectGender" class="text-danger"></span>
    </div>

    <label asp-for="RegistredUser.ImageFile" class="control-label">Image</label>
    <input type="file" asp-for="RegistredUser.ImageFile" class="form-control"/>
    <span asp-validation-for="RegistredUser.ImageFile" ></span>
  
 
    <button type="submit" class="btn btn-primary">Register</button>
</form>

LoginPage/Pages/Response.cshtml
@page
@model LoginPage.Pages.ResponseModel
@{
}
@{
    if (TempData["Message"] != null)
    {
        
    <div class="container d-flex justify-content-center align-items-center vh-100">
    <div class="text-center">
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Success!</h4>
            <p>@TempData["Message"]</p>
            <hr>
            <p class="mb-0">Thank you for your action. You may proceed further or go back to the homepage.</p>
        </div>
        <div class="btn-container">
        <button>
        <a asp-page="/Index" class="btn btn-primary">Go to Homepage</a>
        </button>
        <button>
        <a asp-page=@TempData["link"] class="btn btn-secondary">Continue</a>
        </button>
        </div>
    </div>
        </div>
    }
    else
    {
        <div id="failureMessage" class="alert alert-danger d-none" role="alert">
            <h4 class="alert-heading">Failure!</h4>
            <p>Unfortunately, the operation failed. Please try again.</p>
            <hr>
            <p class="mb-0">You can go back to the homepage or retry the action.</p>
        </div>
    }
}

LoginPage/Pages/Signup.cshtml
@page "/Login"
@model LoginPage.Pages.SignUpModel
@{
    ViewData["Title"] = "SignUp";
}

<div class="container-fluid">
@* 
    @{
        if (TempData["Message"] != null)
        {
            Console.WriteLine(TempData["Message"]);
            <div>
                <p class="text-light bg-success text-center p-3 sticky-top">@TempData["Message"]</p>
            </div>
        }
    } *@
    
    @{
        if (TempData["LoginError"] != null)
        {
            <p class="bg-danger text-light m-4 text-center">@TempData["LoginError"]</p>
        }
    }
    <form  method="post">
<div class="form-group">
        <label asp-for="User.Username" class="control-label">UserName</label>
        <input type="text" asp-for="User.Username" class="form-control" placeholder="Enter the username" />
        <span asp-validation-for="User.Username" class="bg-danger text-light"></span>
</div>
<div class="form-group"> 
        <label asp-for="User.Password" class="control-label"></label>
        <input type="password" asp-for="User.Password" class="form-control" placeholder="Password" />
        <span asp-validation-for="User.Password" class="bg-danger text-light"></span>
</div>
@* <div class="form-group">
@Html.Label("terms","Terms & Conditions");
@Html.CheckBox("terms",false,new{@class="form-check-control"});
</div> *@
<button class="btn btn-primary mt-4">SignUp</button>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}